{% set name = "hyfetch" %}
{% set version = "1.99.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/HyFetch-{{ version }}.tar.gz
  sha256: ddeb422fd797c710f0ad37d584fac466df89e39feddeef765492b2c0b529616e

build:
  skip: true  # [py<37]
  entry_points:
    - hyfetch=hyfetch.main:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - typing-extensions
    - psutil  # [win]
    - colorama >=0.4.6  # [win]
    - git  # [win]

test:
  imports:
    - hyfetch
  commands:
    - pip check
    - hyfetch --help
  requires:
    - pip

about:
  home: https://github.com/hykilpikonna/HyFetch
  summary: Command-line tool that presents system info with LGBTQ+ pride flags
  description: >
    HyFetch is a command line script to display information about your Linux system,  such as amount of installed packages, OS and kernel version, active GTK theme,  CPU info, and used/available memory. It is a fork of neofetch, and adds pride flag  coloration to the OS logo.

    Hyfetch also has the ability to integrate with other system info tools, such as  fastfetch, to use them to gather info that is then displayed through hyfetch.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - EtaoinWu
