context:
  name: hyfetch
  upstream: hykilpikonna
  version: "2.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ upstream }}/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 051acbb25a60ac57e8a8b43159f032a9bcec9b25cd1ed7854899f6ad3bcbd6d5
  patches:
    - 0001-fix-windows-path.patch

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      # TODO add --lock back, remove --debug here
      - cargo auditable install --no-track --debug --bins --root ${{ PREFIX }} --path ./crates/hyfetch
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: hyfetch --help

about:
  homepage: https://github.com/${{ upstream }}/${{ name }}
  repository: https://github.com/${{ upstream }}/${{ name }}
  summary: Command-line tool that presents system info with LGBTQ+ pride flags
  description: >
    HyFetch is a command line script to display information about your Linux system, such as amount of installed packages, OS and kernel version, active GTK theme, CPU info, and used/available memory. It is a fork of neofetch, and adds pride flag coloration to the OS logo.

    Hyfetch also has the ability to integrate with other system info tools, such as fastfetch, to use them to gather info that is then displayed through hyfetch.
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - EtaoinWu
